name: Docker Image Rebuilding
on:
  push:
    branches: [ main ]
jobs:
  compile:
    name: Build and run the container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: awi001/mlops_translator
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: awi001/mlops_translator
          options: -v ${{ github.workspace }}:/data
          run: |
            echo "Love you Mom!"
